import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { slabGeometry, colorFor } from '../src/slab.js'

const root=resolve('..'),base=process.env.WORKBENCH_URL||'http://127.0.0.1:8765',screens=resolve(root,'docs/screens')
await mkdir(screens,{recursive:true})
assert.equal(slabGeometry({length:10000,width:1500,thickness:230},4).y,.92)
assert.equal(colorFor(null,{min:10,max:20}),'#778394')
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']})
const context=await browser.newContext({viewport:{width:1600,height:1050},timezoneId:'Asia/Shanghai'})
const page=await context.newPage(),errors=[],checks=[]
page.on('pageerror',e=>errors.push(e.message))
const numberText=s=>Number(s.replace(/,/g,''))
const post=async(action,fragment)=>{
 const response=page.waitForResponse(r=>r.url().includes(fragment)&&r.request().method()==='POST'&&r.status()===200)
 await action();return (await response).json()
}
try{
 await page.goto(base)
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'数据工作台',exact:true}).click()
 await page.getByTestId('sample-count').waitFor()
 assert.equal((await (await page.request.get(base+'/api/health')).json()).mode,'public_demo','Run browser validation against public demo mode')
 const datasets=await (await page.request.get(base+'/api/datasets')).json()
 assert.equal(datasets.length,1)
 const dataset=datasets[0]
 assert.equal(dataset.source_kind,'sanitized')
 assert.equal(dataset.rows,10000)
 assert.deepEqual(dataset.grades.map(g=>g.name).sort(),['G01','G02','G03','G04','G05'])
 assert.equal(numberText(await page.getByTestId('sample-count').textContent()),10000)
 assert.equal(await page.getByRole('button',{name:'导入数据',exact:true}).count(),0)
 await page.getByTestId('privacy-notice').waitFor()
 await page.waitForFunction(()=>document.querySelectorAll('.chart canvas').length===3)
 assert.equal(await page.locator('canvas').count(),3)
 checks.push('公开演示默认仅提供五类匿名钢种、10,000 条合成记录；有处理标识，无原始上传入口')
 await page.getByLabel('筛选钢种',{exact:true}).selectOption('G01')
 await page.getByLabel('筛选出炉温度下限').fill('1100')
 await page.getByLabel('筛选出炉温度上限').fill('1300')
 const query=await post(()=>page.getByRole('button',{name:'应用筛选',exact:true}).click(),'/query')
 await page.waitForFunction(n=>Number(document.querySelector('[data-testid="sample-count"]').textContent.replaceAll(',',''))===n,query.total)
 assert.ok(query.total>100)
 assert.equal(query.total,query.grades.reduce((n,g)=>n+g.value,0))
 assert.equal(query.total,query.histograms.temp_drop.valid_n)
 assert.ok(query.scatter.every(p=>p[3]==='G01'))
 const target=query.records[1]
 await post(()=>page.locator(`tr[data-id="${target.record_id}"]`).click(),'/records/')
 await page.locator(`.record-details[data-selected-id="${target.record_id}"]`).waitFor()
 await page.getByRole('button',{name:'查看三维示意',exact:true}).click()
 const slab=page.locator('.slab-visual')
 assert.equal(await slab.getAttribute('data-record-id'),target.record_id)
 for(const field of ['length','width','thickness'])assert.equal(Number(await slab.getAttribute('data-'+field)),target[field])
 const color=await slab.getAttribute('data-color')
 await post(()=>page.getByRole('button',{name:'下一页',exact:true}).click(),'/query')
 assert.equal(await slab.getAttribute('data-color'),color)
 await page.getByLabel('三维颜色指标').selectOption('exit_temp')
 await page.getByRole('button',{name:'重置三维视角'}).click()
 await page.getByLabel('三维颜色指标').selectOption('temp_drop')
 await post(()=>page.getByRole('button',{name:'上一页',exact:true}).click(),'/query')
 await page.getByRole('button',{name:'收起三维示意',exact:true}).click()
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:resolve(screens,'workbench.png'),fullPage:true})
 checks.push(`G01 当前筛选 ${query.total} 条，分布、散点、分页表格、三维尺寸及色标一致`)
 const csvResponse=await page.request.post(`${base}/api/datasets/${dataset.id}/export`,{data:query.filters})
 assert.equal(csvResponse.status(),200)
 const csv=await csvResponse.text()
 assert.ok(csv.includes('脱敏合成演示；非真实生产记录'))
 assert.ok(!csv.includes('2023-02'))
 await page.getByRole('button',{name:'分析实验',exact:true}).click()
 await page.getByLabel('分析钢种',{exact:true}).selectOption('G01')
 await page.getByLabel('分组边界').fill('20, 38, 42, 100')
 await page.getByLabel('控制出炉温度下限').fill('1100')
 await page.getByLabel('控制出炉温度上限').fill('1300')
 await page.locator('.control-item').filter({hasText:'粗轧过程时间'}).locator('input[type="checkbox"]').uncheck()
 const result=await post(()=>page.getByRole('button',{name:'运行分析',exact:true}).click(),'/analyses')
 await page.getByTestId('analysis-n').waitFor()
 assert.equal(result.source_kind,'sanitized')
 assert.equal(result.counts.analyzed,result.groups.reduce((n,g)=>n+g.n,0))
 assert.equal(result.counts.analyzed,query.total)
 assert.ok(result.warnings.some(s=>s.includes('脱敏合成演示')))
 await page.locator('.analysis-figure').evaluate(img=>img.decode())
 const report=await page.request.get(base+result.artifacts['report.html'])
 assert.equal(report.status(),200)
 assert.ok((await report.text()).includes('脱敏合成演示'))
 const downloadPromise=page.waitForEvent('download')
 await page.getByRole('link',{name:'下载完整实验包',exact:true}).click()
 const download=await downloadPromise
 assert.equal(await download.failure(),null)
 assert.equal(download.suggestedFilename(),'bundle.zip')
 const rerun=await post(()=>page.getByRole('button',{name:'按保存参数复现',exact:true}).click(),'/rerun')
 assert.deepEqual(rerun.groups,result.groups)
 assert.equal(rerun.samples_sha256,result.samples_sha256)
 await page.locator('.analysis-figure').evaluate(img=>img.decode())
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:resolve(screens,'analysis.png'),fullPage:true})
 const imageResponse=await page.request.get(base+rerun.artifacts['figure.png'])
 await writeFile(resolve(screens,'demo-analysis-figure.png'),await imageResponse.body())
 checks.push(`脱敏分析 ${result.counts.analyzed} 条，图件解码、报告标识、完整实验包下载、保存参数复现通过`)
 const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto(base)
 await mobile.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'数据工作台',exact:true}).click()
 await mobile.getByTestId('sample-count').waitFor();await mobile.getByTestId('privacy-notice').waitFor()
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await mobile.screenshot({path:resolve(screens,'mobile.png'),fullPage:true})
 await mobile.close()
 assert.deepEqual(errors,[])
 await writeFile(resolve(root,'docs/browser-validation.json'),JSON.stringify({mode:'public_demo',dataset_id:dataset.id,rows:dataset.rows,grades:dataset.grades.map(g=>g.name).sort(),checks,analysis_id:rerun.id,analyzed:result.counts.analyzed,errors},null,2))
 console.log(JSON.stringify({checks,errors,analysis_id:rerun.id},null,2))
}finally{await context.close();await browser.close()}
