import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PROCESS_OVERVIEW, PROCESS_STAGES, PROCESS_DURATION, PROCESS_PLAYBACK_RATE, advanceProcessTime, processState } from '../src/process.js'

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..')
const screens=resolve(root,'docs/screens'),checks=[],errors=[]
const base=process.env.WORKBENCH_URL||'http://127.0.0.1:8766'
assert.equal(PROCESS_PLAYBACK_RATE,1.5)
assert.equal(advanceProcessTime(0,2),3,'2 秒实际时间推进 3 秒动画')
assert.ok(Math.abs(advanceProcessTime(31.9,.2)-.2)<1e-10,'循环保留跨越终点的时间')
assert.equal(advanceProcessTime(0,64),0,'多轮推进保持同一循环时钟')
// Motion invariants: finite geometry, continuous boundaries, reversible seek,
// and an actual transition from slab thickness to strip thickness.
for(let t=0;t<=PROCESS_DURATION;t+=.01){
 const s=processState(t)
 for(const v of [s.x,s.y,s.width,s.height,s.progress])assert.ok(Number.isFinite(v))
 assert.ok(s.x-s.width/2>=0&&s.x+s.width/2<=1440)
 assert.ok(s.height>0&&s.height<=18&&s.width>=72)
 assert.equal(s.stage,PROCESS_STAGES.findIndex(stage=>t<stage.end))
}
for(const t of [3,15,19,25]){
 const before=processState(t-1e-6),after=processState(t)
 assert.ok(Math.abs(before.x-after.x)<.001,'阶段边界材料位置连续')
 assert.ok(Math.abs(before.height-after.height)<.001,'阶段边界厚度连续')
}
const pose=processState(21)
processState(30)
assert.deepEqual(processState(21),pose,'反向拖动与首次定位状态一致')
assert.ok(processState(32).height<processState(25).height&&processState(25).height<processState(19).height)
assert.equal(processState(32).stage,4)
checks.push('全时域几何有限、阶段边界连续、反向定位确定、粗轧与精轧确实改变厚度')
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
const context=await browser.newContext({viewport:{width:1600,height:1000}})
const page=await context.newPage()
page.on('pageerror',e=>errors.push(e.message))
const card=page.locator('.process-card')
const tabs=page.getByRole('group',{name:'选择工艺阶段'}).getByRole('button')
async function selectStage(i){await tabs.nth(i+1).click()}
async function seek(t){await page.getByLabel('工艺动画进度').evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))},t)}
try{
 await mkdir(screens,{recursive:true})
 await page.goto(base)
 assert.equal((await (await page.request.get(base+'/api/health')).json()).mode,'public_demo')
 await page.getByTestId('process-home').waitFor()
 assert.equal(await page.getByTestId('sample-count').isVisible(),false)
 assert.equal(await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'工艺概览',exact:true}).getAttribute('aria-current'),'page')
 assert.equal(await card.getAttribute('data-playing'),'true')
 assert.equal(await tabs.count(),6)
 assert.equal(await card.getAttribute('data-selected-stage'),'overview')
 assert.equal(await tabs.nth(0).getAttribute('aria-pressed'),'true')
 assert.equal(await page.getByRole('heading',{name:PROCESS_OVERVIEW.title,exact:true}).isVisible(),true)
 await page.getByLabel('暂停工艺动画',{exact:true}).click()
 const frozen=await card.getAttribute('data-time')
 await page.waitForTimeout(200)
 assert.equal(await card.getAttribute('data-time'),frozen)
 await page.getByLabel('播放工艺动画',{exact:true}).click()
 await page.waitForFunction(t=>Number(document.querySelector('.process-card')?.dataset.time)>Number(t)+.08,frozen)
 const rate=await page.evaluate(async()=>{
  const read=()=>Number(document.querySelector('.process-card').dataset.time)
  const start=read(),wallStart=performance.now()
  await new Promise(resolve=>setTimeout(resolve,600))
  return (read()-start)/((performance.now()-wallStart)/1000)
 })
 assert.ok(rate>1.35&&rate<1.65,`实际播放倍率 ${rate.toFixed(3)} 接近 1.5`)
 for(const [i,s] of PROCESS_STAGES.entries()){
  await selectStage(i)
  assert.equal(await card.getAttribute('data-stage'),s.key)
  assert.equal(await card.getAttribute('data-playing'),'true')
  const start=Number(await card.getAttribute('data-time'))
  assert.ok(start>=s.start&&start<s.start+.5,'从所选阶段起点播放')
  await page.waitForFunction(t=>Number(document.querySelector('.process-card')?.dataset.time)>t+.08,start)
  assert.equal(await page.getByRole('heading',{name:s.title,exact:true}).isVisible(),true)
  assert.equal(await tabs.nth(i+1).getAttribute('aria-pressed'),'true')
  const explanation=await page.locator('.process-explanation').textContent()
  await seek(s.end-.03)
  await page.getByLabel('播放工艺动画',{exact:true}).click()
  const next=PROCESS_STAGES[(i+1)%PROCESS_STAGES.length]
  await page.waitForFunction(key=>document.querySelector('.process-card').dataset.stage===key,next.key)
  assert.equal(await card.getAttribute('data-selected-stage'),s.key,'动画跨阶段后仍保留手动选择')
  assert.equal(await tabs.nth(i+1).getAttribute('aria-pressed'),'true')
  assert.equal(await page.locator('.process-steps button[aria-pressed="true"]').count(),1)
  assert.equal(await page.locator('.process-explanation').textContent(),explanation,'标题、正文和字段不被动画替换')
  assert.equal(await page.getByLabel('工艺动画进度').getAttribute('aria-valuetext'),next.name)

 }
 checks.push('总览默认选中；五工序逐一跨越阶段及末尾循环后，手动标签、标题、正文和字段保持不变，设备和进度仍跟随动画')
 await seek(17)
 assert.equal(await card.getAttribute('data-stage'),'descale')
 assert.equal(await page.locator('.water-jets').getAttribute('opacity'),'1')
 await seek(21)
 assert.equal(Number(await page.locator('.process-material').getAttribute('data-thickness')),Number(pose.height.toFixed(3)))
 await page.getByLabel('重播工艺动画',{exact:true}).click()
 assert.ok(Number(await card.getAttribute('data-time'))<.5)
 assert.equal(await card.getAttribute('data-selected-stage'),'finish','重播不改变手动标签')
 for(let cycle=0;cycle<2;cycle++){
  await seek(31.97)
  await page.getByLabel('播放工艺动画',{exact:true}).click()
  await page.waitForFunction(()=>Number(document.querySelector('.process-card')?.dataset.time)<1)
  assert.equal(await card.getAttribute('data-playing'),'true')
  assert.equal(await card.getAttribute('data-stage'),'charge')
 }
 await seek(32)
 await page.getByLabel('播放工艺动画',{exact:true}).click()
 await page.waitForFunction(()=>Number(document.querySelector('.process-card')?.dataset.time)<1)
 assert.equal(await card.getAttribute('data-playing'),'true')
 checks.push('默认首页自动播放；实测 1.5 倍速；两次跨越终点自动循环；五阶段按钮从阶段起点自动播放；末帧继续、暂停冻结、拖动及重播通过')
 await selectStage(0)
 await seek(1.4)
 assert.equal(await page.getByText('装炉辊道',{exact:true}).isVisible(),true)
 assert.equal(await page.getByText('装炉口',{exact:true}).isVisible(),true)
 assert.equal(await page.locator('.charge-rollers circle').count(),5)
 assert.equal(await page.locator('.charge-frame,.descaler-frame,.door-label-line').count(),0,'辊道竖向支撑和标注引线已移除')
 await page.screenshot({path:resolve(screens,'process-entry.png'),fullPage:true})
 await selectStage(1)
 await seek(10)
 assert.equal(await page.getByText('烟气逆向 · 余热用于预热助燃空气',{exact:true}).isVisible(),true)
 assert.equal(await page.locator('.heat-recovery,.recovered-air,.gas-particles,.air-particles').count(),0)
 const staticGas=await page.locator('.furnace-gas').innerHTML()
 await seek(12)
 assert.equal(await page.locator('.furnace-gas').innerHTML(),staticGas,'烟气部分不随动画进度变化')
 await seek(10)
 assert.deepEqual(await page.locator('.equipment-heading').evaluateAll(nodes=>nodes.map(n=>n.dataset.step)),['01','02','03','04','05'])
 await page.screenshot({path:resolve(screens,'process-overview.png'),fullPage:true})
 checks.push('工艺图 01—05 与步骤编号一致；烟气仅保留静态逆向箭头和余热利用文字，无回收设备、空气回路或流动粒子')
 await selectStage(-1)
 await seek(10)
 await page.getByLabel('播放工艺动画',{exact:true}).click()
 const overviewTime=Number(await card.getAttribute('data-time'))
 await page.waitForFunction(t=>Number(document.querySelector('.process-card').dataset.time)>t+.1,overviewTime)
 assert.equal(await card.getAttribute('data-selected-stage'),'overview')
 await page.screenshot({path:resolve(screens,'process-total-overview.png'),fullPage:true})
 await selectStage(1)
 await seek(20.5)
 await page.getByLabel('播放工艺动画',{exact:true}).click()
 assert.equal(await card.getAttribute('data-stage'),'rough')
 assert.equal(await card.getAttribute('data-selected-stage'),'heat')
 await page.screenshot({path:resolve(screens,'process-tab-pinned.png'),fullPage:true})
 checks.push('总览可重选并继续播放；辊道保留全部轮子，移除竖向支撑及交叉标注引线')
 await selectStage(3)
 await seek(22)
 await page.screenshot({path:resolve(screens,'process-rough.png'),fullPage:true})
 await page.getByRole('button',{name:'进入数据工作台',exact:false}).click()
 await page.getByTestId('sample-count').waitFor()
 assert.equal((await page.getByTestId('sample-count').textContent()).replaceAll(',',''),'10000')
 assert.equal(await page.getByTestId('process-home').count(),0)
 await page.getByLabel('筛选钢种',{exact:true}).selectOption('G02')
 const response=page.waitForResponse(r=>r.url().endsWith('/query')&&r.request().method()==='POST'&&r.status()===200)
 await page.getByRole('button',{name:'应用筛选',exact:true}).click()
 const query=await (await response).json()
 await page.waitForFunction(n=>Number(document.querySelector('[data-testid="sample-count"]').textContent.replaceAll(',',''))===n,query.total)
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'工艺概览',exact:true}).click()
 await page.getByRole('button',{name:'进入数据工作台',exact:false}).click()
 assert.equal(Number((await page.getByTestId('sample-count').textContent()).replaceAll(',','')),query.total)
 assert.equal(await page.getByLabel('筛选钢种',{exact:true}).inputValue(),'G02')
 await page.waitForFunction(()=>[...document.querySelectorAll('.chart canvas')].length===3&&[...document.querySelectorAll('.chart canvas')].every(n=>n.getBoundingClientRect().width>300&&Math.abs(n.getBoundingClientRect().width-n.closest('.chart').getBoundingClientRect().width)<1))
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'工艺概览',exact:true}).click()
 await page.getByRole('button',{name:'进入厚度与温降分析',exact:false}).click()
 await page.getByLabel('分析钢种',{exact:true}).waitFor()
 checks.push('首页两个入口可用；返回首页不会清空筛选，图表正确恢复尺寸')
 for(const width of [1280,768,390]){
  await page.setViewportSize({width,height:844})
  await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'工艺概览',exact:true}).click()
  await page.getByLabel('暂停工艺动画',{exact:true}).click()
  for(const i of [-1,0,1,2,3,4]){
   await selectStage(i)
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}px 第 ${i+1} 阶段无整页溢出`)
   assert.ok((await page.locator('.rolling-svg').boundingBox()).width<=width)
  }
  if(width===390){
   await selectStage(-1)
   await seek(10)
   await page.screenshot({path:resolve(screens,'process-mobile-total.png'),fullPage:true})
   await selectStage(0)
   await seek(1.4)
   await page.screenshot({path:resolve(screens,'process-mobile-entry.png'),fullPage:true})
   await selectStage(1)
   await seek(10)
   assert.equal(await page.locator('.charging').isVisible(),false,'手机加热阶段不显示被截断的装炉标签')
   assert.equal(await page.locator('.descaler').isVisible(),false,'手机加热阶段不显示被截断的除鳞标签')
   const heatBox=await page.locator('.rolling-svg').boundingBox()
   for(const name of ['烟气逆向 · 余热用于预热助燃空气']){
    const box=await page.getByText(name,{exact:true}).boundingBox()
    assert.ok(box.x>=heatBox.x&&box.x+box.width<=heatBox.x+heatBox.width,`手机端 ${name} 不被裁切`)
   }
   await page.screenshot({path:resolve(screens,'process-mobile.png'),fullPage:true})
   await selectStage(3)
   await seek(22)
   await page.screenshot({path:resolve(screens,'process-mobile-rough.png'),fullPage:true})
  }
  await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'数据工作台',exact:true}).click()
 }
 const reduced=await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'reduce'})
 const reducedPage=await reduced.newPage()
 reducedPage.on('pageerror',e=>errors.push(e.message))
 await reducedPage.goto(base)
 await reducedPage.getByTestId('process-home').waitFor()
 assert.equal(await reducedPage.locator('.process-card').getAttribute('data-playing'),'false')
 assert.equal(Number(await reducedPage.locator('.process-card').getAttribute('data-time')),0)
 await reducedPage.getByLabel('播放工艺动画',{exact:true}).click()
 assert.equal(await reducedPage.locator('.process-card').getAttribute('data-playing'),'true')
 await reducedPage.getByLabel('暂停工艺动画',{exact:true}).click()
 await reducedPage.getByRole('group',{name:'选择工艺阶段'}).getByRole('button').nth(4).click()
 assert.equal(await reducedPage.locator('.process-card').getAttribute('data-playing'),'true','明确选择阶段后仍按请求播放')
 await reduced.close()
 checks.push('1600 / 1280 / 768 / 390px 无整页横向溢出；手机按阶段聚焦设备；减少动态偏好默认暂停，仍可手动播放')
 assert.deepEqual(errors,[])
 await writeFile(resolve(root,'docs/process-validation.json'),JSON.stringify({checks,errors},null,2))
 console.log(JSON.stringify({checks,errors},null,2))
}finally{await browser.close()}
